use db
--------------------------------------DATA PREPARARTION AND UNDERSTANDING --------------------------------------------------------------------------

--Q1.what is the total number of rows in each of the 3 tables?

SELECT
(SELECT COUNT (*) FROM Customer)+
(SELECT COUNT (*) FROM TRANSACTIONS)+
(SELECT COUNT (*) FROM prod_cat_info) as TOTAL_ROWS
 
 --Q2. What is the total number of transactions that have a return?

Select COUNT(*) AS TOTAL_RETURNED_TRANSCATION
FROM Transactions

--Q3.As you would have noticed, the dates provided across the datasets are not in a correct format. As first steps, pls 
--convert the date variables into valid date formats before proceeding ahead.

	 SELECT CONVERT (VARCHAR, DOB ,103) AS FORMATTEDDATE FROM Customer
	 UNION ALL
	 SELECT CONVERT (VARCHAR ,TRAN_DATE ,103) AS FROMATTEDDATE FROM Transactions

--Q4.What is the time range of the transaction data available for analysis? 
--Show the output in number of days, months and years simultaneously in different columns.

	SELECT 
	DATEDIFF(YEAR,MIN(TRAN_DATE),MAX(TRAN_DATE))AS YEARS,
	DATEDIFF(MONTH,MIN(TRAN_DATE),MAX(TRAN_DATE))AS MONTHS,
	DATEDIFF(DAY,MIN(TRAN_DATE),MAX(TRAN_DATE)) AS DAYS FROM Transactions

--Q5.Which product category does the sub-category “DIY” belong to?

 SELECT prod_cat FROM prod_cat_info 
 WHERE prod_subcat = 'DIY'

------------------------------------------------------DATA ANALYSIS------------------------------------------------------------------------------------


--1.	Which channel is most frequently used for transactions?

SELECT TOP 1 Store_type AS CHANNEL,COUNT(STORE_TYPE) AS 'FREQUENCY'
FROM Transactions
GROUP BY Store_type
ORDER BY 'FREQUENCY' DESC


--2.What is the count of Male and Female customers in the database?

SELECT GENDER ,COUNT(CUSTOMER_ID)AS CUSTOMER_COUNT FROM Customer
WHERE Gender IN ('M','F' )
GROUP BY Gender

--3.From which city do we have the maximum number of customers and how many?

 SELECT TOP 1 city_code,COUNT(customer_Id)AS CUSTOMER_COUNT FROM Customer
 GROUP BY city_code
 ORDER BY CUSTOMER_COUNT DESC 

--4. How many sub-categories are there under the Books category?

SELECT COUNT(prod_subcat) AS SUB_CATEGORIES_COUNT
FROM prod_cat_info
WHERE prod_cat='BOOKS'
group by prod_cat 

--5. What is the maximum quantity of products ever ordered?

SELECT TOP 1 QTY 
FROM Transactions
ORDER BY QTY DESC

--6. What is the net total revenue generated in categories Electronics and Books

SELECT SUM(total_amt) as AMOUNT FROM Transactions as T
inner join prod_cat_info  AS PC  on T.prod_cat_code = PC.prod_cat_code
and prod_sub_cat_code = prod_subcat_code
where prod_cat in ('books' , 'electronics')

--7. How many customers have >10 transactions with us, excluding returns?

select count(CUSTOMER_ID) AS CUSTOMER_COUNT
FROM CUSTOMER 
WHERE customer_Id IN 
(
SELECT CUST_ID FROM Transactions
LEFT JOIN Customer ON customer_Id =cust_id
WHERE total_amt NOT LIKE '-%'
GROUP BY cust_id
HAVING COUNT(TRANSACTION_ID)>10)

--8..What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?

SELECT SUM(TOTAL_AMT) AS AMOUNT FROM Transactions AS T
INNER JOIN prod_cat_info AS PC
ON T.prod_cat_code = PC.prod_cat_code
AND prod_subcat_code = prod_sub_cat_code
WHERE prod_cat IN ('CLOTHING','ELECTRONICS') AND Store_type ='flagship store'


--9. What is the total revenue generated from “Male” customers 
--in “Electronics” category? Output should display total revenue by prod sub-cat.

SELECT SUM(total_amt) AS REVENUE FROM Transactions AS T
INNER JOIN prod_cat_info AS PC
ON PC.prod_cat_code = T.prod_cat_code
LEFT JOIN Customer AS C 
ON C.customer_Id =T.cust_id AND PC.prod_sub_cat_code = T.prod_subcat_code
WHERE Gender ='M' AND prod_cat ='electronics'

--10. What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?


--11. For all customers aged between 25 to 35 years find what is the 
--net total revenue generated by these consumers in last 30 days of transactions from max transaction date available in the data?

SELECT CUST_ID ,SUM(TOTAL_AMT) AS REVENUE FROM Transactions
WHERE cust_id IN 
(
   SELECT CUSTOMER_ID FROM Customer 
   WHERE DATEDIFF (YEAR,CONVERT (DATE ,DOB,103),GETDATE()) BETWEEN 25 AND 35)
   AND 
   CONVERT (DATE,tran_date,103) BETWEEN DATEADD(DAY,-30,(SELECT MAX(CONVERT(DATE,TRAN_DATE,103)) FROM TRANSACTIONS))
   AND (SELECT MAX(CONVERT (DATE,TRAN_DATE,103)) FROM Transactions)
   GROUP BY cust_id

--12. Which product category has seen the max value of returns in the last 3 months of transactions?

 SELECT TOP 1 PROD_CAT , SUM(total_amt) from Transactions T
 INNER JOIN prod_cat_info PC ON 
 T.prod_cat_code = PC.prod_cat_code AND T.prod_subcat_code = PC.prod_sub_cat_code
 WHERE total_amt < 0 AND 
 CONVERT (DATE,TRAN_DATE,103) BETWEEN DATEADD (MONTH,-3,(SELECT MAX(CONVERT(DATE,TRAN_DATE,103)) FROM Transactions))
 AND (SELECT MAX(CONVERT(DATE,TRAN_DATE,103)) FROM Transactions) 
 GROUP BY PROD_CAT
 ORDER BY 2 DESC

 --13.Which store-type sells the maximum products; by value of sales amount and by quantity sold?

 SELECT STORE_TYPE , SUM(TOTAL_AMT) AS TOTAL_SALES,SUM(QTY)AS TOTAL_QUAN FROM Transactions
 GROUP BY Store_type
 HAVING SUM(total_amt) >= ALL (SELECT SUM(total_amt) FROM Transactions GROUP BY Store_type)
 AND SUM(Qty) >= ALL (SELECT SUM(Qty) FROM Transactions GROUP BY Store_type)
 
--14.	What are the categories for which average revenue is above the overall average.

SELECT prod_cat ,AVG(TOTAL_AMT) AS AVERAGE FROM Transactions AS T
INNER JOIN prod_cat_info AS PC
ON T.prod_cat_code = PC.prod_cat_code AND T.prod_subcat_code = PC.prod_sub_cat_code
GROUP BY prod_cat
HAVING AVG(TOTAL_AMT) > (SELECT AVG(total_amt) FROM Transactions)


--15.Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.

SELECT prod_cat , prod_subcat ,AVG(TOTAL_AMT) AS AVERAGE_REVENUE ,SUM(TOTAL_AMT) AS REVENUE FROM Transactions AS T
INNER JOIN prod_cat_info AS PC
ON T.prod_cat_code =PC.prod_cat_code AND T.prod_subcat_code =PC.prod_sub_cat_code
WHERE prod_cat IN
(
SELECT TOP 5 prod_cat FROM Transactions AS T
INNER JOIN prod_cat_info AS PC
ON T.prod_cat_code =PC.prod_cat_code AND T.prod_subcat_code =PC.prod_sub_cat_code 
GROUP BY prod_cat
ORDER BY SUM(Qty) DESC
)
GROUP BY prod_cat , prod_subcat




 
















